config:
  aws:profile: iac
  aws:region: eu-central-1
  aws:skipCredentialsValidation: "true"
  web:accountId: "865039251033"
  web:includeWWW: "true"
  web:pathToWebsiteContents: ../../apps/web/build
  web:targetDomain: freedev.app
