on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
env:
  AWS_REGION: 'eu-central-1'
  # See AWS Console > {your-username} at the top right > Account ID
  AWS_ACCOUNT_ID: '865039251033'
  # See https://authjs.dev/reference/sveltekit/#:~:text=AUTH_SECRET%20environment%20variable
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  # See https://authjs.dev/reference/sveltekit/#:~:text=AUTH_TRUST_HOST
  AUTH_TRUST_HOST: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  deployment:
    name: Deploy to AWS
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # GITHUB_ACTIONS_ROLE_TO_ASSUME GitHubActionRole
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionRole
          role-session-name: serverless-workflows-deployment
          aws-region: ${{ env.AWS_REGION }}
      - name: Build
        run: npm run build
      
      
# https://turbo.build/repo/docs/ci/github-actions
  # build:
  #     name: Build and Test
  #     timeout-minutes: 15
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Check out code
  #         uses: actions/checkout@v3
  #         with:
  #           fetch-depth: 2
 
  #       - name: Setup Node.js environment
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: 16
  #           cache: 'npm'
 
  #       - name: Install dependencies
  #         run: npm install
 
  #       - name: Build
  #         run: npm run build
 
  #       - name: Test
  #         run: npm run test